# Generated by Django 5.0.6 on 2024-08-25 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_groupcart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcart',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='groupcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='groupcart',
            name='vote_down',
        ),
        migrations.RemoveField(
            model_name='groupcart',
            name='vote_up',
        ),
        migrations.AddField(
            model_name='groupcart',
            name='name',
            field=models.CharField(default='asdf', max_length=100),
        ),
        migrations.CreateModel(
            name='GroupCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_up', models.IntegerField(default=0)),
                ('vote_down', models.IntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.groupcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
