# Generated by Django 5.0.6 on 2024-08-25 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_groupcart_is_selected_and_more'),
        ('users', '0002_nonregistereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='groupcartitem',
            name='non_registed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.nonregistereduser'),
        ),
        migrations.AddField(
            model_name='groupcartitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='groupcart',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orderstatus'),
        ),
    ]
